In [1]:
import numpy as np
import pandas as pd
import json
import re
from operator import add
from ua_parser import user_agent_parser
from IPython.display import display
from sklearn.linear_model import LinearRegression
import sklearn.svm as svm
from plotly import __version__
from plotly.offline import download_plotlyjs, init_notebook_mode, plot, iplot
from plotly.graph_objs import Scatter, Figure, Layout, Bar, Margin
init_notebook_mode(connected=True)

def cpu_core_filter(text):
    regex = r'Core Count: ([0-9])'
    pattern = re.compile(regex)
    match = pattern.search(text.replace('\n', ''))
    if match == None:
        return 0
    return int(match.group(1))

def cpu_thread_filter(text):
    regex = r'Thread Count: ([0-9])'
    pattern = re.compile(regex)
    match = pattern.search(text.replace('\n', ''))
    if match == None:
        return 0
    return int(match.group(1))

df = pd.read_json('data.json')
# display(df)

cpu = np.array(list(df.apply((lambda x:
                 [cpu_core_filter(x.smbios), cpu_thread_filter(x.smbios)]
                 ), axis=1)))
display(cpu)

worker = df.apply((lambda x:
                  json.loads(x.worker)
                 ), axis=1)

X = np.array(list(worker.apply((lambda x:
                 list(np.array(x) / x[0])
             ))))

display(X)

Y = cpu

array([[4, 8],
       [2, 4],
       [2, 4],
       [4, 4],
       [0, 0],
       [2, 4],
       [2, 4],
       [2, 4],
       [2, 4],
       [2, 4],
       [2, 4],
       [2, 4],
       [4, 8],
       [4, 4],
       [2, 4],
       [4, 8],
       [2, 4],
       [4, 4],
       [0, 0],
       [2, 4],
       [2, 2],
       [2, 2],
       [4, 8],
       [4, 8],
       [4, 8],
       [4, 8],
       [2, 4],
       [2, 0],
       [2, 4],
       [4, 8],
       [2, 4],
       [4, 8],
       [2, 4],
       [2, 4],
       [2, 4],
       [2, 0],
       [2, 2],
       [4, 4],
       [4, 4],
       [0, 0],
       [4, 0],
       [2, 4],
       [4, 8],
       [2, 2],
       [2, 4],
       [4, 4],
       [2, 2],
       [2, 4],
       [2, 4],
       [2, 4],
       [2, 4],
       [2, 4],
       [2, 4],
       [2, 4],
       [2, 4],
       [2, 4],
       [2, 4],
       [2, 4],
       [2, 4],
       [2, 4],
       [2, 4]])

array([[  1.        ,   0.94895985,   7.3733672 ],
       [  1.        ,   0.06352418,   0.49476773],
       [  1.        ,   0.03496893,   0.1856043 ],
       [  1.        ,   0.24541052,   1.27755857],
       [  1.        ,   0.52467452,   3.36884236],
       [  1.        ,   0.96046932,   1.42691731],
       [  1.        ,   0.51181378,   3.21832714],
       [  1.        ,   0.49123386,   2.99987624],
       [  1.        ,   0.15154963,   1.05330195],
       [  1.        ,   0.4802244 ,   3.64804648],
       [  1.        ,   0.69131998,   0.74627632],
       [  1.        ,   0.51619057,   2.61242787],
       [  1.        ,   0.33861305,   1.41744577],
       [  1.        ,   0.54651915,   1.96515554],
       [  1.        ,   0.12037175,   0.62190581],
       [  1.        ,   0.4655819 ,   1.93059175],
       [  1.        ,   0.07196337,   0.43107654],
       [  1.        ,   0.03321686,   0.20020654],
       [  1.        ,   0.22158311,   1.01718558],
       [  1.        ,   0.24325

In [2]:
trim_sample = [6, 20, 29, 37, 41, 42]
X_trimmed = np.delete(X, trim_sample, 0)
Y_trimmed = np.delete(Y, trim_sample, 0)
display(X_trimmed)
display(Y_trimmed)


array([[  1.        ,   0.94895985,   7.3733672 ],
       [  1.        ,   0.06352418,   0.49476773],
       [  1.        ,   0.03496893,   0.1856043 ],
       [  1.        ,   0.24541052,   1.27755857],
       [  1.        ,   0.52467452,   3.36884236],
       [  1.        ,   0.96046932,   1.42691731],
       [  1.        ,   0.49123386,   2.99987624],
       [  1.        ,   0.15154963,   1.05330195],
       [  1.        ,   0.4802244 ,   3.64804648],
       [  1.        ,   0.69131998,   0.74627632],
       [  1.        ,   0.51619057,   2.61242787],
       [  1.        ,   0.33861305,   1.41744577],
       [  1.        ,   0.54651915,   1.96515554],
       [  1.        ,   0.12037175,   0.62190581],
       [  1.        ,   0.4655819 ,   1.93059175],
       [  1.        ,   0.07196337,   0.43107654],
       [  1.        ,   0.03321686,   0.20020654],
       [  1.        ,   0.22158311,   1.01718558],
       [  1.        ,   0.24325011,   0.85174254],
       [  1.        ,   0.05457

array([[4, 8],
       [2, 4],
       [2, 4],
       [4, 4],
       [0, 0],
       [2, 4],
       [2, 4],
       [2, 4],
       [2, 4],
       [2, 4],
       [2, 4],
       [4, 8],
       [4, 4],
       [2, 4],
       [4, 8],
       [2, 4],
       [4, 4],
       [0, 0],
       [2, 4],
       [2, 2],
       [4, 8],
       [4, 8],
       [4, 8],
       [4, 8],
       [2, 4],
       [2, 0],
       [2, 4],
       [2, 4],
       [4, 8],
       [2, 4],
       [2, 4],
       [2, 4],
       [2, 0],
       [2, 2],
       [4, 4],
       [0, 0],
       [4, 0],
       [2, 2],
       [2, 4],
       [4, 4],
       [2, 2],
       [2, 4],
       [2, 4],
       [2, 4],
       [2, 4],
       [2, 4],
       [2, 4],
       [2, 4],
       [2, 4],
       [2, 4],
       [2, 4],
       [2, 4],
       [2, 4],
       [2, 4],
       [2, 4]])

In [3]:
clf = LinearRegression()
clf.fit(X, Y)
display(clf.coef_)
display(clf.intercept_)
display(clf.score(X_trimmed, Y_trimmed))

array([[ 0.        ,  1.19763275, -0.1044326 ],
       [ 0.        ,  2.49703472, -0.19302254]])

array([ 2.25779717,  3.62636039])

0.059938094619483122

In [4]:
data = worker.apply((lambda x: 
              Scatter(
                  x=list([1, 2, 16]),
                  y=list(np.array(x) / x[0]),
                  mode='lines'
              )))

layout = Layout(
    margin=Margin(
        l=20,
        r=20,
        b=20,
        t=20,
        pad=4
    ),
    showlegend=False
)

fig = Figure(data=data.tolist(), layout=layout)

iplot(fig, image='svg')

In [5]:
aes = np.array(list(df.apply((lambda x:
                 x.aes
                 ), axis=1)))
aes
last_worker = np.array(list(worker.apply((lambda x:
                 x[2]
             ))))
display(aes)
display(last_worker)
aes / last_worker

array([   369.48      ,    443.41      ,    538.31      ,    660.31891838,
          891.765     ,   3517.11      ,    567.81      ,    704.59      ,
          810.37512885,    628.135     ,    381.1       ,    677.685     ,
          401.585     ,    371.7       ,    667.2       ,    393.115     ,
         2549.50732091,    566.405     ,   1384.485     ,   1522.47      ,
         3618.47      ,   3278.42      ,    389.355     ,    338.415     ,
         1698.465     ,    354.41      ,    545.07      ,  12235.995     ,
          757.15989944,    531.9       ,    605.76      ,    302.67      ,
         1904.3530142 ,    513.475     ,    574.575     ,   9913.995     ,
         1107.8452309 ,    671.49114522,    477.13      ,    400.1       ,
          958.305     ,    679.34991305,    637.255     ,   1570.685     ,
          747.30469773,   2247.        ,   1579.39      ,   3182.005     ,
          624.62986635,    600.67976591,    733.58014599,    797.21497362,
          685.67482511,  

array([  304.815     ,   184.63      ,    90.045     ,   599.5039532 ,
         382.97      ,  1526.88      ,   229.515     ,   363.6       ,
         298.68511747,   455.185     ,   145.3       ,   273.9       ,
         156.16      ,   136.765     ,   104.39      ,   151.87      ,
        1172.45932569,    70.76      ,   578.27      ,   301.585     ,
         267.95      ,   243.7       ,   138.545     ,   110.205     ,
         219.1       ,   129.955     ,   217.28      ,  2465.        ,
         341.10023774,   246.855     ,    96.        ,    92.11      ,
        1217.29103439,   567.185     ,   297.445     ,  2452.005     ,
        2932.78007873,   782.05559541,   155.03      ,   134.2       ,
         195.865     ,   224.5301116 ,    48.35      ,   755.405     ,
         794.55074368,   492.        ,   816.505     ,  1582.475     ,
         295.35001203,   333.47996457,   904.83490546,   532.78509464,
         806.13999457,   671.64473314,   432.535     ,   314.62      ,
      

array([  1.21214507,   2.40161404,   5.97823311,   1.10144214,
         2.32855054,   2.30346196,   2.47395595,   1.93781628,
         2.71314197,   1.3799554 ,   2.62284928,   2.47420591,
         2.57162526,   2.71780061,   6.3914168 ,   2.58849674,
         2.17449532,   8.00459299,   2.39418438,   5.04822853,
        13.50427319,  13.45268773,   2.81031434,   3.07077719,
         7.75200822,   2.72717479,   2.50860641,   4.96389249,
         2.21975776,   2.1547062 ,   6.31      ,   3.28596244,
         1.56441883,   0.90530427,   1.93170166,   4.04321973,
         0.37774576,   0.85862329,   3.07766239,   2.98137109,
         4.89268118,   3.0256517 ,  13.18004137,   2.07926212,
         0.94053741,   4.56707317,   1.93432986,   2.01077742,
         2.11488011,   1.80124694,   0.81073369,   1.49631621,
         0.85056545,   0.89986571,   1.52284786,   3.21347975,
         1.27846298,   1.44240737,   1.91777241,   3.37160844,   3.09235989])

In [15]:
# tmp = pd.Series(aes / last_worker)
tmp = aes / last_worker
aes_ni = np.delete(tmp, [24, 25, 47, 50, 22, 31, 39, 40, 49], 0)
n_aes_ni = np.delete(tmp, [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 23, 26, 27, 28, 29, 30, 32, 33, 34, 35, 36, 37, 38, 41, 42, 43, 44, 45, 46, 48, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 22, 31, 39, 40, 49], 0)
data = [Bar(
            x=list(range(1, len(aes_ni))),
            y=aes_ni,
    name = 'with AES-NI',
        ),
       Bar(
            x=list(range(len(aes_ni), len(aes_ni)+len(n_aes_ni))),
            y=n_aes_ni,
           name = 'without AES-NI',
       )]

layout = Layout(
    margin=Margin(
        l=20,
        r=20,
        b=20,
        t=20,
        pad=4
    )
)

fig = Figure(data=data, layout=layout)

iplot(fig, image='svg')

/opt/conda/lib/python3.6/site-packages/ipykernel_launcher.py:4: DeprecationWarning:

in the future out of bounds indices will raise an error instead of being ignored by `numpy.delete`.

