In [1]:
!pip install plotly
import numpy as np
import pandas as pd
import json
import re
from operator import add
from ua_parser import user_agent_parser
from IPython.display import display
from sklearn.linear_model import LinearRegression
from plotly import __version__
from plotly.offline import download_plotlyjs, init_notebook_mode, plot, iplot
from plotly.graph_objs import Scatter, Figure, Layout, Bar, Margin
init_notebook_mode(connected=True)

def memory_speed_filter(text):
    regex = r'type 17.+ ([0-9]+) (MH|MT)'
    pattern = re.compile(regex)
    match = pattern.search(text.replace('\n', ''))
    return int(match.group(1))

def cpu_speed_filter(text):
    regex = r'type 4.+Current Speed: ([0-9]+) MH'
    pattern = re.compile(regex)
    match = pattern.search(text.replace('\n', ''))
    return int(match.group(1))

def browser_filter(text):
    parsed_string = user_agent_parser.ParseUserAgent(text)
    family = parsed_string['family']
    if family == "Chrome":
        return 1.3343400040036402
    elif family == "Firefox":
        return 1.0
    elif family == "IE":
        return 9.28240479500004
    elif family == "Opera":
        return 1.0579772683237236
    elif family == "Edge":
        return 9.34620244713113
    elif family == "Safari":
        return 2.770657343907221
    else:
        return 0

df = pd.read_json('data.json')

memory_origin = df.apply((lambda x:
                  json.loads(x.memory)
                 ), axis=1)
memory = np.array(list(memory_origin.apply((lambda x:
                 list(np.array(x) / x[0])
             ))))
browser = np.array([list(df.apply((lambda x:
                 browser_filter(x.userAgent)
                 ), axis=1))])
cpu =  np.array([list(df.apply((lambda x:
                  cpu_speed_filter(x.smbios)
                 ), axis=1))])
temp = np.concatenate((memory, browser.T), axis=1)
X = np.concatenate((temp, cpu.T), axis=1)

# display(X)

speed = df.apply((lambda x:
                  [memory_speed_filter(x.smbios)]
                 ), axis=1)

Y = np.array(list(speed))

# display(X)
# display(Y)

# X_trimmed = np.delete(X, [8, 10, 24, 27, 36, 39, 40, 47, 50], 0)
# Y_trimmed = np.delete(Y, [8, 10, 24, 27, 36, 39, 40, 47, 50], 0)

# X_trimmed = np.delete(X, [0], 1)
# Y_trimmed = Y

# display(X_trimmed)
# display(Y_trimmed)
display(memory)

array([[  1.00000000e+00,   8.09589041e+00,   7.26712329e+01,
          7.30835616e+02],
       [  1.00000000e+00,   4.88307692e+00,   5.42830769e+01,
          5.46230769e+02],
       [  1.00000000e+00,   5.05345912e+00,   3.65110063e+01,
          2.83644654e+02],
       [  1.00000000e+00,   7.50973806e+01,   7.53443781e+02,
          7.55348049e+03],
       [  1.00000000e+00,   9.74375000e+00,   8.88125000e+01,
          8.09293750e+02],
       [  1.00000000e+00,   7.26593807e+00,   7.15100182e+01,
          6.05254098e+02],
       [  1.00000000e+00,   8.29464286e+00,   6.65178571e+01,
          6.93750000e+02],
       [  1.00000000e+00,   6.33139535e+00,   5.57151163e+01,
          5.04232558e+02],
       [  1.00000000e+00,   1.31770424e+01,   1.27401738e+02,
          8.20678112e+02],
       [  1.00000000e+00,   7.27777778e+00,   5.87055556e+01,
          5.00711111e+02],
       [  1.00000000e+00,   1.55000000e+01,   1.52000000e+02,
          1.62000000e+03],
       [  1.00000000e

In [5]:
display(df)

aes  endian                              gpgpu  \
0     369.480000       1                   [384.915,112.29]   
1     443.410000       1                 [3520.92,1284.675]   
2     538.310000       1                 [2409.72,1206.315]   
3     660.318918       1                                 []   
4     891.765000       1                 [1370.83,1293.135]   
5    3517.110000       1                [6681.685,5990.255]   
6     567.810000       1                  [1189.685,232.68]   
7     704.590000       1                  [840.43,1588.095]   
8     810.375129       1  [1832.9398415277,3451.3952435318]   
9     628.135000       1                   [2240.605,964.7]   
10    381.100000       1                      [493.9,208.1]   
11    677.685000       1                  [675.645,186.045]   
12    401.585000       1                 [547.655,2075.145]   
13    371.700000       1                   [519.24,786.055]   
14    667.200000       1                [1674.005,4551.305]   
15    393.115000       1                   [526.98,2120.26]   
16   2549.507321       1                                 []   
17    566.405000       1                   [1186.38,1181.3]   
18   1384.485000       1                 [1396.295,2872.92]   
19   1522.470000       1                 [1486.68,1246.825]   
20   3618.470000       1                [3951.665,2105.105]   
21   3278.420000       1                [3950.125,2014.565]   
22    389.355000       1                  [560.605,560.405]   
23    338.415000       1                    [428.5,666.315]   
24   1698.465000       1                 [654.895,1016.445]   
25    354.410000       1                   [506.075,751.07]   
26    545.070000       1                   [716.235,232.23]   
27  12235.995000       1                    [9835.995,5856]   
28    757.159899       1   [2770.545297532,1769.8502569389]   
29    531.900000       1                [1290.61,11201.055]   
..           ...     ...                                ...   
31    302.670000       1                    [476.93,650.81]   
32   1904.353014       1                                 []   
33    513.475000       1                [1393.955,3912.445]   
34    574.575000       1                   [734.71,1061.74]   
35   9913.995000       1                [8197.995,2164.005]   
36   1107.845231       1  [5753.2200816356,1365.7098596363]   
37    671.491145       1                                 []   
38    477.130000       1                 [1746.96,1123.035]   
39    400.100000       1                         [955.9,91]   
40    958.305000       1                 [927.285,1664.025]   
41    679.349913       1  [1809.0652237357,1107.5299050922]   
42    637.255000       1                [1947.575,2993.705]   
43   1570.685000       1                  [2028.94,9389.34]   
44    747.304698       1                                 []   
45   2247.000000       1                        [2273,1662]   
46   1579.390000       1                [1994.555,9270.085]   
47   3182.005000       1                [4655.695,4303.525]   
48    624.629866       1  [2073.8500896854,1350.4749657386]   
49    600.679766       1  [1404.4248784426,1323.6849695445]   
50    733.580146       1  [1482.8851053953,1218.8097867177]   
51    797.214974       1  [2495.3548760362,1711.9400208555]   
52    685.674825       1  [1799.4750288854,1721.0600286379]   
53    604.390062       1  [1638.1897712553,1346.0649353087]   
54    658.685000       1                  [1769.13,5398.66]   
55   1011.025000       1                 [973.395,1228.935]   
56    341.030000       1                  [495.045,896.575]   
57    505.095000       1                      [750.1,904.9]   
58   1589.679805       1  [6387.5650528904,2056.3049850204]   
59   1235.070382       1  [6765.5999991357,2375.7499246429]   
60   1330.720414       1  [3443.3303838728,1276.8398205259]   

                                                  gpu  id  \
0   {"webGLVendor":"ATI Technologies Inc.","w

In [2]:
clf = LinearRegression()
clf.fit(X, Y)
display(clf.coef_)
display(clf.intercept_)
display(clf.score(X, Y))

# clf = LinearRegression()
# clf.fit(X_trimmed, Y_trimmed)
# display(clf.coef_)
# display(clf.intercept_)
# display(clf.score(X_trimmed, Y_trimmed))

array([[  0.00000000e+00,  -1.08715715e+01,  -1.22470890e-02,
          2.32967948e-02,   8.40669482e+01,  -1.10269572e-03]])

array([ 1726.89712574])

0.11677570456521313

In [3]:
data = memory_origin.apply((lambda x: 
              Scatter(
                  x=list([10, 1024, 1024*10, 1024*100]),
                  y=list(np.array(x) / x[0]),
                  mode='lines'
              )))

layout = Layout(
    margin=Margin(
        l=20,
        r=20,
        b=20,
        t=20,
        pad=4
    ),
    showlegend=False
)

fig = Figure(data=data.tolist(), layout=layout)

iplot(fig, image='svg')